### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by bfarago** [moths/lxi-control#1]
HI,
Just... I've quickly go through your source, and stop at the first findings.
line 258: config.command[strlen(config.command)] = 0;
-config.command declared as a pointer, it could be null_ptr as well. Writing it here before check. (Major)
-optarg returns a zero terminated string already (or null_ptr), so zero termination is pointless.
-strlen() also looking for zero termination to determine the length, therefore the complete line is pointless.
Suggested change:
check if  (NULL_PTR != config.command) then check strlen() only if there is a limitation in the protocol  for the length.  Handle these error cases ie by report to user.
Minor:
line 255 and 261: retval gets value twice unconditionally.
send() return type is ssize_t. Even if it is int, best practice to declare as the same type.
line 262:  better to use "if (const == var)" to reduce a human factor of the failure.

**Comment by moths** [comment]
Fixed in  cc2dd69, thanks.
